### ISSUE TITLE
Add a CLI command that calculates initialFund value

### ISSUE THREAD

**Issue by VadimSaveljev** [paritytech/uniques-campaign-runner#7]
Currently we need to do this manually

**Comment by hamidra** [comment]
We can either add a separate command or instead of adding a new command, we can add an inquiry to ask the user if they want to set the initial-fund to some value if it was not already specified in the workflow.json file and then add calculate it base on some multiplier of the tx fees for that chain.

refs to  how it is currently done in the code:
https://github.com/paritytech/uniques-campaign-runner/blob/b5eb2136901dfd599c13380c607a6fdbf0317e18/src/workflow/workflow.js#L93

**Comment by VadimSaveljev** [comment]
Fixed in PRs 8-11
